# Generated by Django 3.0.4 on 2020-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intramural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ans1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='ans2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='que1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='que2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
