# Generated by Django 3.0.4 on 2020-04-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intramural', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('sport', 'team1', 'team2', 'date', 'time')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='court',
        ),
    ]
