# Generated by Django 3.0.4 on 2020-04-28 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intramural', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(default='', max_length=50)),
                ('score_1', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_2', models.CharField(default='', max_length=50)),
                ('score_2', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('active', models.CharField(default='Y', max_length=1)),
            ],
        ),
    ]
