# Generated by Django 3.0.4 on 2020-05-06 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intramural', '0002_auto_20200429_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='intramural.Teams'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='intramural.Teams'),
        ),
    ]
